// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: paigow.proto

#ifndef PROTOBUF_paigow_2eproto__INCLUDED
#define PROTOBUF_paigow_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
namespace proto3_proto {
class Ack;
class AckDefaultTypeInternal;
extern AckDefaultTypeInternal _Ack_default_instance_;
class C2S_Login;
class C2S_LoginDefaultTypeInternal;
extern C2S_LoginDefaultTypeInternal _C2S_Login_default_instance_;
class C2S_PG_Bet;
class C2S_PG_BetDefaultTypeInternal;
extern C2S_PG_BetDefaultTypeInternal _C2S_PG_Bet_default_instance_;
class C2S_PG_Collocation;
class C2S_PG_CollocationDefaultTypeInternal;
extern C2S_PG_CollocationDefaultTypeInternal _C2S_PG_Collocation_default_instance_;
class C2S_PG_GrabBanker;
class C2S_PG_GrabBankerDefaultTypeInternal;
extern C2S_PG_GrabBankerDefaultTypeInternal _C2S_PG_GrabBanker_default_instance_;
class C2S_PG_StartGame;
class C2S_PG_StartGameDefaultTypeInternal;
extern C2S_PG_StartGameDefaultTypeInternal _C2S_PG_StartGame_default_instance_;
class C2S_PG_Sure;
class C2S_PG_SureDefaultTypeInternal;
extern C2S_PG_SureDefaultTypeInternal _C2S_PG_Sure_default_instance_;
class PaiGowConfig;
class PaiGowConfigDefaultTypeInternal;
extern PaiGowConfigDefaultTypeInternal _PaiGowConfig_default_instance_;
class PaiGowPlayer;
class PaiGowPlayerDefaultTypeInternal;
extern PaiGowPlayerDefaultTypeInternal _PaiGowPlayer_default_instance_;
class PaiGowResult;
class PaiGowResultDefaultTypeInternal;
extern PaiGowResultDefaultTypeInternal _PaiGowResult_default_instance_;
class PaiGowSnapshot;
class PaiGowSnapshotDefaultTypeInternal;
extern PaiGowSnapshotDefaultTypeInternal _PaiGowSnapshot_default_instance_;
class PlayerInfo;
class PlayerInfoDefaultTypeInternal;
extern PlayerInfoDefaultTypeInternal _PlayerInfo_default_instance_;
class S2C_Error;
class S2C_ErrorDefaultTypeInternal;
extern S2C_ErrorDefaultTypeInternal _S2C_Error_default_instance_;
class S2C_InitUserInfo;
class S2C_InitUserInfoDefaultTypeInternal;
extern S2C_InitUserInfoDefaultTypeInternal _S2C_InitUserInfo_default_instance_;
class S2C_PG_AddPlayer;
class S2C_PG_AddPlayerDefaultTypeInternal;
extern S2C_PG_AddPlayerDefaultTypeInternal _S2C_PG_AddPlayer_default_instance_;
class S2C_PG_Bet;
class S2C_PG_BetDefaultTypeInternal;
extern S2C_PG_BetDefaultTypeInternal _S2C_PG_Bet_default_instance_;
class S2C_PG_Collocation;
class S2C_PG_CollocationDefaultTypeInternal;
extern S2C_PG_CollocationDefaultTypeInternal _S2C_PG_Collocation_default_instance_;
class S2C_PG_Deal;
class S2C_PG_DealDefaultTypeInternal;
extern S2C_PG_DealDefaultTypeInternal _S2C_PG_Deal_default_instance_;
class S2C_PG_GrabBanker;
class S2C_PG_GrabBankerDefaultTypeInternal;
extern S2C_PG_GrabBankerDefaultTypeInternal _S2C_PG_GrabBanker_default_instance_;
class S2C_PG_Result;
class S2C_PG_ResultDefaultTypeInternal;
extern S2C_PG_ResultDefaultTypeInternal _S2C_PG_Result_default_instance_;
class S2C_PG_StartGame;
class S2C_PG_StartGameDefaultTypeInternal;
extern S2C_PG_StartGameDefaultTypeInternal _S2C_PG_StartGame_default_instance_;
class UserInfo;
class UserInfoDefaultTypeInternal;
extern UserInfoDefaultTypeInternal _UserInfo_default_instance_;
}  // namespace proto3_proto

namespace proto3_proto {

namespace protobuf_paigow_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_paigow_2eproto

// ===================================================================

class PaiGowConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.PaiGowConfig) */ {
 public:
  PaiGowConfig();
  virtual ~PaiGowConfig();

  PaiGowConfig(const PaiGowConfig& from);

  inline PaiGowConfig& operator=(const PaiGowConfig& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PaiGowConfig& default_instance();

  static inline const PaiGowConfig* internal_default_instance() {
    return reinterpret_cast<const PaiGowConfig*>(
               &_PaiGowConfig_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PaiGowConfig* other);

  // implements Message ----------------------------------------------

  inline PaiGowConfig* New() const PROTOBUF_FINAL { return New(NULL); }

  PaiGowConfig* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PaiGowConfig& from);
  void MergeFrom(const PaiGowConfig& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PaiGowConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 pot = 1;
  void clear_pot();
  static const int kPotFieldNumber = 1;
  ::google::protobuf::uint32 pot() const;
  void set_pot(::google::protobuf::uint32 value);

  // uint32 banker_type = 2;
  void clear_banker_type();
  static const int kBankerTypeFieldNumber = 2;
  ::google::protobuf::uint32 banker_type() const;
  void set_banker_type(::google::protobuf::uint32 value);

  // uint32 lock_bet_num = 4;
  void clear_lock_bet_num();
  static const int kLockBetNumFieldNumber = 4;
  ::google::protobuf::uint32 lock_bet_num() const;
  void set_lock_bet_num(::google::protobuf::uint32 value);

  // uint32 type = 5;
  void clear_type();
  static const int kTypeFieldNumber = 5;
  ::google::protobuf::uint32 type() const;
  void set_type(::google::protobuf::uint32 value);

  // bool is_bet_always = 3;
  void clear_is_bet_always();
  static const int kIsBetAlwaysFieldNumber = 3;
  bool is_bet_always() const;
  void set_is_bet_always(bool value);

  // bool has_ghost = 6;
  void clear_has_ghost();
  static const int kHasGhostFieldNumber = 6;
  bool has_ghost() const;
  void set_has_ghost(bool value);

  // bool has_heaven_nine = 7;
  void clear_has_heaven_nine();
  static const int kHasHeavenNineFieldNumber = 7;
  bool has_heaven_nine() const;
  void set_has_heaven_nine(bool value);

  // @@protoc_insertion_point(class_scope:proto3_proto.PaiGowConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 pot_;
  ::google::protobuf::uint32 banker_type_;
  ::google::protobuf::uint32 lock_bet_num_;
  ::google::protobuf::uint32 type_;
  bool is_bet_always_;
  bool has_ghost_;
  bool has_heaven_nine_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PaiGowPlayer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.PaiGowPlayer) */ {
 public:
  PaiGowPlayer();
  virtual ~PaiGowPlayer();

  PaiGowPlayer(const PaiGowPlayer& from);

  inline PaiGowPlayer& operator=(const PaiGowPlayer& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PaiGowPlayer& default_instance();

  static inline const PaiGowPlayer* internal_default_instance() {
    return reinterpret_cast<const PaiGowPlayer*>(
               &_PaiGowPlayer_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(PaiGowPlayer* other);

  // implements Message ----------------------------------------------

  inline PaiGowPlayer* New() const PROTOBUF_FINAL { return New(NULL); }

  PaiGowPlayer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PaiGowPlayer& from);
  void MergeFrom(const PaiGowPlayer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PaiGowPlayer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 hand_cards = 2;
  int hand_cards_size() const;
  void clear_hand_cards();
  static const int kHandCardsFieldNumber = 2;
  ::google::protobuf::uint32 hand_cards(int index) const;
  void set_hand_cards(int index, ::google::protobuf::uint32 value);
  void add_hand_cards(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      hand_cards() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_hand_cards();

  // repeated uint32 chips = 5;
  int chips_size() const;
  void clear_chips();
  static const int kChipsFieldNumber = 5;
  ::google::protobuf::uint32 chips(int index) const;
  void set_chips(int index, ::google::protobuf::uint32 value);
  void add_chips(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      chips() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_chips();

  // .proto3_proto.PlayerInfo player = 1;
  bool has_player() const;
  void clear_player();
  static const int kPlayerFieldNumber = 1;
  const ::proto3_proto::PlayerInfo& player() const;
  ::proto3_proto::PlayerInfo* mutable_player();
  ::proto3_proto::PlayerInfo* release_player();
  void set_allocated_player(::proto3_proto::PlayerInfo* player);

  // bool is_banker = 3;
  void clear_is_banker();
  static const int kIsBankerFieldNumber = 3;
  bool is_banker() const;
  void set_is_banker(bool value);

  // uint32 status = 4;
  void clear_status();
  static const int kStatusFieldNumber = 4;
  ::google::protobuf::uint32 status() const;
  void set_status(::google::protobuf::uint32 value);

  // int32 score = 6;
  void clear_score();
  static const int kScoreFieldNumber = 6;
  ::google::protobuf::int32 score() const;
  void set_score(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto3_proto.PaiGowPlayer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > hand_cards_;
  mutable int _hand_cards_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > chips_;
  mutable int _chips_cached_byte_size_;
  ::proto3_proto::PlayerInfo* player_;
  bool is_banker_;
  ::google::protobuf::uint32 status_;
  ::google::protobuf::int32 score_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PaiGowResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.PaiGowResult) */ {
 public:
  PaiGowResult();
  virtual ~PaiGowResult();

  PaiGowResult(const PaiGowResult& from);

  inline PaiGowResult& operator=(const PaiGowResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PaiGowResult& default_instance();

  static inline const PaiGowResult* internal_default_instance() {
    return reinterpret_cast<const PaiGowResult*>(
               &_PaiGowResult_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(PaiGowResult* other);

  // implements Message ----------------------------------------------

  inline PaiGowResult* New() const PROTOBUF_FINAL { return New(NULL); }

  PaiGowResult* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PaiGowResult& from);
  void MergeFrom(const PaiGowResult& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PaiGowResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 hand_cards = 3;
  int hand_cards_size() const;
  void clear_hand_cards();
  static const int kHandCardsFieldNumber = 3;
  ::google::protobuf::uint32 hand_cards(int index) const;
  void set_hand_cards(int index, ::google::protobuf::uint32 value);
  void add_hand_cards(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      hand_cards() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_hand_cards();

  // uint32 seat_id = 1;
  void clear_seat_id();
  static const int kSeatIdFieldNumber = 1;
  ::google::protobuf::uint32 seat_id() const;
  void set_seat_id(::google::protobuf::uint32 value);

  // int32 result = 2;
  void clear_result();
  static const int kResultFieldNumber = 2;
  ::google::protobuf::int32 result() const;
  void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:proto3_proto.PaiGowResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > hand_cards_;
  mutable int _hand_cards_cached_byte_size_;
  ::google::protobuf::uint32 seat_id_;
  ::google::protobuf::int32 result_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class PaiGowSnapshot : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.PaiGowSnapshot) */ {
 public:
  PaiGowSnapshot();
  virtual ~PaiGowSnapshot();

  PaiGowSnapshot(const PaiGowSnapshot& from);

  inline PaiGowSnapshot& operator=(const PaiGowSnapshot& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PaiGowSnapshot& default_instance();

  static inline const PaiGowSnapshot* internal_default_instance() {
    return reinterpret_cast<const PaiGowSnapshot*>(
               &_PaiGowSnapshot_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(PaiGowSnapshot* other);

  // implements Message ----------------------------------------------

  inline PaiGowSnapshot* New() const PROTOBUF_FINAL { return New(NULL); }

  PaiGowSnapshot* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const PaiGowSnapshot& from);
  void MergeFrom(const PaiGowSnapshot& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(PaiGowSnapshot* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 public_cards = 3;
  int public_cards_size() const;
  void clear_public_cards();
  static const int kPublicCardsFieldNumber = 3;
  ::google::protobuf::uint32 public_cards(int index) const;
  void set_public_cards(int index, ::google::protobuf::uint32 value);
  void add_public_cards(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      public_cards() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_public_cards();

  // repeated .proto3_proto.PaiGowPlayer players = 4;
  int players_size() const;
  void clear_players();
  static const int kPlayersFieldNumber = 4;
  const ::proto3_proto::PaiGowPlayer& players(int index) const;
  ::proto3_proto::PaiGowPlayer* mutable_players(int index);
  ::proto3_proto::PaiGowPlayer* add_players();
  ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowPlayer >*
      mutable_players();
  const ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowPlayer >&
      players() const;

  // repeated .proto3_proto.PaiGowResult results = 5;
  int results_size() const;
  void clear_results();
  static const int kResultsFieldNumber = 5;
  const ::proto3_proto::PaiGowResult& results(int index) const;
  ::proto3_proto::PaiGowResult* mutable_results(int index);
  ::proto3_proto::PaiGowResult* add_results();
  ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult >*
      mutable_results();
  const ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult >&
      results() const;

  // int64 room_owner = 2;
  void clear_room_owner();
  static const int kRoomOwnerFieldNumber = 2;
  ::google::protobuf::int64 room_owner() const;
  void set_room_owner(::google::protobuf::int64 value);

  // uint32 state = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::uint32 state() const;
  void set_state(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto3_proto.PaiGowSnapshot)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > public_cards_;
  mutable int _public_cards_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowPlayer > players_;
  ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult > results_;
  ::google::protobuf::int64 room_owner_;
  ::google::protobuf::uint32 state_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class S2C_PG_AddPlayer : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.S2C_PG_AddPlayer) */ {
 public:
  S2C_PG_AddPlayer();
  virtual ~S2C_PG_AddPlayer();

  S2C_PG_AddPlayer(const S2C_PG_AddPlayer& from);

  inline S2C_PG_AddPlayer& operator=(const S2C_PG_AddPlayer& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_PG_AddPlayer& default_instance();

  static inline const S2C_PG_AddPlayer* internal_default_instance() {
    return reinterpret_cast<const S2C_PG_AddPlayer*>(
               &_S2C_PG_AddPlayer_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(S2C_PG_AddPlayer* other);

  // implements Message ----------------------------------------------

  inline S2C_PG_AddPlayer* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C_PG_AddPlayer* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C_PG_AddPlayer& from);
  void MergeFrom(const S2C_PG_AddPlayer& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C_PG_AddPlayer* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .proto3_proto.PaiGowPlayer player = 1;
  bool has_player() const;
  void clear_player();
  static const int kPlayerFieldNumber = 1;
  const ::proto3_proto::PaiGowPlayer& player() const;
  ::proto3_proto::PaiGowPlayer* mutable_player();
  ::proto3_proto::PaiGowPlayer* release_player();
  void set_allocated_player(::proto3_proto::PaiGowPlayer* player);

  // @@protoc_insertion_point(class_scope:proto3_proto.S2C_PG_AddPlayer)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::proto3_proto::PaiGowPlayer* player_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class C2S_PG_StartGame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.C2S_PG_StartGame) */ {
 public:
  C2S_PG_StartGame();
  virtual ~C2S_PG_StartGame();

  C2S_PG_StartGame(const C2S_PG_StartGame& from);

  inline C2S_PG_StartGame& operator=(const C2S_PG_StartGame& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S_PG_StartGame& default_instance();

  static inline const C2S_PG_StartGame* internal_default_instance() {
    return reinterpret_cast<const C2S_PG_StartGame*>(
               &_C2S_PG_StartGame_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(C2S_PG_StartGame* other);

  // implements Message ----------------------------------------------

  inline C2S_PG_StartGame* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S_PG_StartGame* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S_PG_StartGame& from);
  void MergeFrom(const C2S_PG_StartGame& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S_PG_StartGame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto3_proto.C2S_PG_StartGame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class S2C_PG_StartGame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.S2C_PG_StartGame) */ {
 public:
  S2C_PG_StartGame();
  virtual ~S2C_PG_StartGame();

  S2C_PG_StartGame(const S2C_PG_StartGame& from);

  inline S2C_PG_StartGame& operator=(const S2C_PG_StartGame& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_PG_StartGame& default_instance();

  static inline const S2C_PG_StartGame* internal_default_instance() {
    return reinterpret_cast<const S2C_PG_StartGame*>(
               &_S2C_PG_StartGame_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(S2C_PG_StartGame* other);

  // implements Message ----------------------------------------------

  inline S2C_PG_StartGame* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C_PG_StartGame* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C_PG_StartGame& from);
  void MergeFrom(const S2C_PG_StartGame& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C_PG_StartGame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool is_grab = 1;
  void clear_is_grab();
  static const int kIsGrabFieldNumber = 1;
  bool is_grab() const;
  void set_is_grab(bool value);

  // @@protoc_insertion_point(class_scope:proto3_proto.S2C_PG_StartGame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool is_grab_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class C2S_PG_GrabBanker : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.C2S_PG_GrabBanker) */ {
 public:
  C2S_PG_GrabBanker();
  virtual ~C2S_PG_GrabBanker();

  C2S_PG_GrabBanker(const C2S_PG_GrabBanker& from);

  inline C2S_PG_GrabBanker& operator=(const C2S_PG_GrabBanker& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S_PG_GrabBanker& default_instance();

  static inline const C2S_PG_GrabBanker* internal_default_instance() {
    return reinterpret_cast<const C2S_PG_GrabBanker*>(
               &_C2S_PG_GrabBanker_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(C2S_PG_GrabBanker* other);

  // implements Message ----------------------------------------------

  inline C2S_PG_GrabBanker* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S_PG_GrabBanker* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S_PG_GrabBanker& from);
  void MergeFrom(const C2S_PG_GrabBanker& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S_PG_GrabBanker* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool is_grab = 1;
  void clear_is_grab();
  static const int kIsGrabFieldNumber = 1;
  bool is_grab() const;
  void set_is_grab(bool value);

  // @@protoc_insertion_point(class_scope:proto3_proto.C2S_PG_GrabBanker)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool is_grab_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class S2C_PG_GrabBanker : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.S2C_PG_GrabBanker) */ {
 public:
  S2C_PG_GrabBanker();
  virtual ~S2C_PG_GrabBanker();

  S2C_PG_GrabBanker(const S2C_PG_GrabBanker& from);

  inline S2C_PG_GrabBanker& operator=(const S2C_PG_GrabBanker& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_PG_GrabBanker& default_instance();

  static inline const S2C_PG_GrabBanker* internal_default_instance() {
    return reinterpret_cast<const S2C_PG_GrabBanker*>(
               &_S2C_PG_GrabBanker_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(S2C_PG_GrabBanker* other);

  // implements Message ----------------------------------------------

  inline S2C_PG_GrabBanker* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C_PG_GrabBanker* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C_PG_GrabBanker& from);
  void MergeFrom(const S2C_PG_GrabBanker& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C_PG_GrabBanker* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool is_grab = 1;
  void clear_is_grab();
  static const int kIsGrabFieldNumber = 1;
  bool is_grab() const;
  void set_is_grab(bool value);

  // @@protoc_insertion_point(class_scope:proto3_proto.S2C_PG_GrabBanker)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool is_grab_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class C2S_PG_Bet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.C2S_PG_Bet) */ {
 public:
  C2S_PG_Bet();
  virtual ~C2S_PG_Bet();

  C2S_PG_Bet(const C2S_PG_Bet& from);

  inline C2S_PG_Bet& operator=(const C2S_PG_Bet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S_PG_Bet& default_instance();

  static inline const C2S_PG_Bet* internal_default_instance() {
    return reinterpret_cast<const C2S_PG_Bet*>(
               &_C2S_PG_Bet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(C2S_PG_Bet* other);

  // implements Message ----------------------------------------------

  inline C2S_PG_Bet* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S_PG_Bet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S_PG_Bet& from);
  void MergeFrom(const C2S_PG_Bet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S_PG_Bet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 chips = 1;
  int chips_size() const;
  void clear_chips();
  static const int kChipsFieldNumber = 1;
  ::google::protobuf::uint32 chips(int index) const;
  void set_chips(int index, ::google::protobuf::uint32 value);
  void add_chips(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      chips() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_chips();

  // @@protoc_insertion_point(class_scope:proto3_proto.C2S_PG_Bet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > chips_;
  mutable int _chips_cached_byte_size_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class S2C_PG_Bet : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.S2C_PG_Bet) */ {
 public:
  S2C_PG_Bet();
  virtual ~S2C_PG_Bet();

  S2C_PG_Bet(const S2C_PG_Bet& from);

  inline S2C_PG_Bet& operator=(const S2C_PG_Bet& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_PG_Bet& default_instance();

  static inline const S2C_PG_Bet* internal_default_instance() {
    return reinterpret_cast<const S2C_PG_Bet*>(
               &_S2C_PG_Bet_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    10;

  void Swap(S2C_PG_Bet* other);

  // implements Message ----------------------------------------------

  inline S2C_PG_Bet* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C_PG_Bet* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C_PG_Bet& from);
  void MergeFrom(const S2C_PG_Bet& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C_PG_Bet* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 chips = 2;
  int chips_size() const;
  void clear_chips();
  static const int kChipsFieldNumber = 2;
  ::google::protobuf::uint32 chips(int index) const;
  void set_chips(int index, ::google::protobuf::uint32 value);
  void add_chips(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      chips() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_chips();

  // int64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:proto3_proto.S2C_PG_Bet)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > chips_;
  mutable int _chips_cached_byte_size_;
  ::google::protobuf::int64 user_id_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class S2C_PG_Deal : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.S2C_PG_Deal) */ {
 public:
  S2C_PG_Deal();
  virtual ~S2C_PG_Deal();

  S2C_PG_Deal(const S2C_PG_Deal& from);

  inline S2C_PG_Deal& operator=(const S2C_PG_Deal& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_PG_Deal& default_instance();

  static inline const S2C_PG_Deal* internal_default_instance() {
    return reinterpret_cast<const S2C_PG_Deal*>(
               &_S2C_PG_Deal_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    11;

  void Swap(S2C_PG_Deal* other);

  // implements Message ----------------------------------------------

  inline S2C_PG_Deal* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C_PG_Deal* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C_PG_Deal& from);
  void MergeFrom(const S2C_PG_Deal& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C_PG_Deal* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 my_card = 1;
  int my_card_size() const;
  void clear_my_card();
  static const int kMyCardFieldNumber = 1;
  ::google::protobuf::uint32 my_card(int index) const;
  void set_my_card(int index, ::google::protobuf::uint32 value);
  void add_my_card(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      my_card() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_my_card();

  // @@protoc_insertion_point(class_scope:proto3_proto.S2C_PG_Deal)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > my_card_;
  mutable int _my_card_cached_byte_size_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class C2S_PG_Collocation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.C2S_PG_Collocation) */ {
 public:
  C2S_PG_Collocation();
  virtual ~C2S_PG_Collocation();

  C2S_PG_Collocation(const C2S_PG_Collocation& from);

  inline C2S_PG_Collocation& operator=(const C2S_PG_Collocation& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S_PG_Collocation& default_instance();

  static inline const C2S_PG_Collocation* internal_default_instance() {
    return reinterpret_cast<const C2S_PG_Collocation*>(
               &_C2S_PG_Collocation_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    12;

  void Swap(C2S_PG_Collocation* other);

  // implements Message ----------------------------------------------

  inline C2S_PG_Collocation* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S_PG_Collocation* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S_PG_Collocation& from);
  void MergeFrom(const C2S_PG_Collocation& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S_PG_Collocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 first = 1;
  int first_size() const;
  void clear_first();
  static const int kFirstFieldNumber = 1;
  ::google::protobuf::uint32 first(int index) const;
  void set_first(int index, ::google::protobuf::uint32 value);
  void add_first(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      first() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_first();

  // repeated uint32 end = 2;
  int end_size() const;
  void clear_end();
  static const int kEndFieldNumber = 2;
  ::google::protobuf::uint32 end(int index) const;
  void set_end(int index, ::google::protobuf::uint32 value);
  void add_end(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      end() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_end();

  // @@protoc_insertion_point(class_scope:proto3_proto.C2S_PG_Collocation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > first_;
  mutable int _first_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > end_;
  mutable int _end_cached_byte_size_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class S2C_PG_Collocation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.S2C_PG_Collocation) */ {
 public:
  S2C_PG_Collocation();
  virtual ~S2C_PG_Collocation();

  S2C_PG_Collocation(const S2C_PG_Collocation& from);

  inline S2C_PG_Collocation& operator=(const S2C_PG_Collocation& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_PG_Collocation& default_instance();

  static inline const S2C_PG_Collocation* internal_default_instance() {
    return reinterpret_cast<const S2C_PG_Collocation*>(
               &_S2C_PG_Collocation_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    13;

  void Swap(S2C_PG_Collocation* other);

  // implements Message ----------------------------------------------

  inline S2C_PG_Collocation* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C_PG_Collocation* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C_PG_Collocation& from);
  void MergeFrom(const S2C_PG_Collocation& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C_PG_Collocation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 cards = 2;
  int cards_size() const;
  void clear_cards();
  static const int kCardsFieldNumber = 2;
  ::google::protobuf::uint32 cards(int index) const;
  void set_cards(int index, ::google::protobuf::uint32 value);
  void add_cards(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      cards() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_cards();

  // uint32 seat_id = 1;
  void clear_seat_id();
  static const int kSeatIdFieldNumber = 1;
  ::google::protobuf::uint32 seat_id() const;
  void set_seat_id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:proto3_proto.S2C_PG_Collocation)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > cards_;
  mutable int _cards_cached_byte_size_;
  ::google::protobuf::uint32 seat_id_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class S2C_PG_Result : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.S2C_PG_Result) */ {
 public:
  S2C_PG_Result();
  virtual ~S2C_PG_Result();

  S2C_PG_Result(const S2C_PG_Result& from);

  inline S2C_PG_Result& operator=(const S2C_PG_Result& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const S2C_PG_Result& default_instance();

  static inline const S2C_PG_Result* internal_default_instance() {
    return reinterpret_cast<const S2C_PG_Result*>(
               &_S2C_PG_Result_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    14;

  void Swap(S2C_PG_Result* other);

  // implements Message ----------------------------------------------

  inline S2C_PG_Result* New() const PROTOBUF_FINAL { return New(NULL); }

  S2C_PG_Result* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const S2C_PG_Result& from);
  void MergeFrom(const S2C_PG_Result& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(S2C_PG_Result* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .proto3_proto.PaiGowResult scores = 1;
  int scores_size() const;
  void clear_scores();
  static const int kScoresFieldNumber = 1;
  const ::proto3_proto::PaiGowResult& scores(int index) const;
  ::proto3_proto::PaiGowResult* mutable_scores(int index);
  ::proto3_proto::PaiGowResult* add_scores();
  ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult >*
      mutable_scores();
  const ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult >&
      scores() const;

  // repeated uint32 public_cards = 2;
  int public_cards_size() const;
  void clear_public_cards();
  static const int kPublicCardsFieldNumber = 2;
  ::google::protobuf::uint32 public_cards(int index) const;
  void set_public_cards(int index, ::google::protobuf::uint32 value);
  void add_public_cards(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      public_cards() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_public_cards();

  // @@protoc_insertion_point(class_scope:proto3_proto.S2C_PG_Result)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult > scores_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > public_cards_;
  mutable int _public_cards_cached_byte_size_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class C2S_PG_Sure : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:proto3_proto.C2S_PG_Sure) */ {
 public:
  C2S_PG_Sure();
  virtual ~C2S_PG_Sure();

  C2S_PG_Sure(const C2S_PG_Sure& from);

  inline C2S_PG_Sure& operator=(const C2S_PG_Sure& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const C2S_PG_Sure& default_instance();

  static inline const C2S_PG_Sure* internal_default_instance() {
    return reinterpret_cast<const C2S_PG_Sure*>(
               &_C2S_PG_Sure_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    15;

  void Swap(C2S_PG_Sure* other);

  // implements Message ----------------------------------------------

  inline C2S_PG_Sure* New() const PROTOBUF_FINAL { return New(NULL); }

  C2S_PG_Sure* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const C2S_PG_Sure& from);
  void MergeFrom(const C2S_PG_Sure& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(C2S_PG_Sure* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto3_proto.C2S_PG_Sure)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_paigow_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PaiGowConfig

// uint32 pot = 1;
inline void PaiGowConfig::clear_pot() {
  pot_ = 0u;
}
inline ::google::protobuf::uint32 PaiGowConfig::pot() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowConfig.pot)
  return pot_;
}
inline void PaiGowConfig::set_pot(::google::protobuf::uint32 value) {
  
  pot_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowConfig.pot)
}

// uint32 banker_type = 2;
inline void PaiGowConfig::clear_banker_type() {
  banker_type_ = 0u;
}
inline ::google::protobuf::uint32 PaiGowConfig::banker_type() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowConfig.banker_type)
  return banker_type_;
}
inline void PaiGowConfig::set_banker_type(::google::protobuf::uint32 value) {
  
  banker_type_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowConfig.banker_type)
}

// bool is_bet_always = 3;
inline void PaiGowConfig::clear_is_bet_always() {
  is_bet_always_ = false;
}
inline bool PaiGowConfig::is_bet_always() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowConfig.is_bet_always)
  return is_bet_always_;
}
inline void PaiGowConfig::set_is_bet_always(bool value) {
  
  is_bet_always_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowConfig.is_bet_always)
}

// uint32 lock_bet_num = 4;
inline void PaiGowConfig::clear_lock_bet_num() {
  lock_bet_num_ = 0u;
}
inline ::google::protobuf::uint32 PaiGowConfig::lock_bet_num() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowConfig.lock_bet_num)
  return lock_bet_num_;
}
inline void PaiGowConfig::set_lock_bet_num(::google::protobuf::uint32 value) {
  
  lock_bet_num_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowConfig.lock_bet_num)
}

// uint32 type = 5;
inline void PaiGowConfig::clear_type() {
  type_ = 0u;
}
inline ::google::protobuf::uint32 PaiGowConfig::type() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowConfig.type)
  return type_;
}
inline void PaiGowConfig::set_type(::google::protobuf::uint32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowConfig.type)
}

// bool has_ghost = 6;
inline void PaiGowConfig::clear_has_ghost() {
  has_ghost_ = false;
}
inline bool PaiGowConfig::has_ghost() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowConfig.has_ghost)
  return has_ghost_;
}
inline void PaiGowConfig::set_has_ghost(bool value) {
  
  has_ghost_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowConfig.has_ghost)
}

// bool has_heaven_nine = 7;
inline void PaiGowConfig::clear_has_heaven_nine() {
  has_heaven_nine_ = false;
}
inline bool PaiGowConfig::has_heaven_nine() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowConfig.has_heaven_nine)
  return has_heaven_nine_;
}
inline void PaiGowConfig::set_has_heaven_nine(bool value) {
  
  has_heaven_nine_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowConfig.has_heaven_nine)
}

// -------------------------------------------------------------------

// PaiGowPlayer

// .proto3_proto.PlayerInfo player = 1;
inline bool PaiGowPlayer::has_player() const {
  return this != internal_default_instance() && player_ != NULL;
}
inline void PaiGowPlayer::clear_player() {
  if (GetArenaNoVirtual() == NULL && player_ != NULL) delete player_;
  player_ = NULL;
}
inline const ::proto3_proto::PlayerInfo& PaiGowPlayer::player() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowPlayer.player)
  return player_ != NULL ? *player_
                         : *::proto3_proto::PlayerInfo::internal_default_instance();
}
inline ::proto3_proto::PlayerInfo* PaiGowPlayer::mutable_player() {
  
  if (player_ == NULL) {
    player_ = new ::proto3_proto::PlayerInfo;
  }
  // @@protoc_insertion_point(field_mutable:proto3_proto.PaiGowPlayer.player)
  return player_;
}
inline ::proto3_proto::PlayerInfo* PaiGowPlayer::release_player() {
  // @@protoc_insertion_point(field_release:proto3_proto.PaiGowPlayer.player)
  
  ::proto3_proto::PlayerInfo* temp = player_;
  player_ = NULL;
  return temp;
}
inline void PaiGowPlayer::set_allocated_player(::proto3_proto::PlayerInfo* player) {
  delete player_;
  player_ = player;
  if (player) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:proto3_proto.PaiGowPlayer.player)
}

// repeated uint32 hand_cards = 2;
inline int PaiGowPlayer::hand_cards_size() const {
  return hand_cards_.size();
}
inline void PaiGowPlayer::clear_hand_cards() {
  hand_cards_.Clear();
}
inline ::google::protobuf::uint32 PaiGowPlayer::hand_cards(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowPlayer.hand_cards)
  return hand_cards_.Get(index);
}
inline void PaiGowPlayer::set_hand_cards(int index, ::google::protobuf::uint32 value) {
  hand_cards_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowPlayer.hand_cards)
}
inline void PaiGowPlayer::add_hand_cards(::google::protobuf::uint32 value) {
  hand_cards_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.PaiGowPlayer.hand_cards)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
PaiGowPlayer::hand_cards() const {
  // @@protoc_insertion_point(field_list:proto3_proto.PaiGowPlayer.hand_cards)
  return hand_cards_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
PaiGowPlayer::mutable_hand_cards() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.PaiGowPlayer.hand_cards)
  return &hand_cards_;
}

// bool is_banker = 3;
inline void PaiGowPlayer::clear_is_banker() {
  is_banker_ = false;
}
inline bool PaiGowPlayer::is_banker() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowPlayer.is_banker)
  return is_banker_;
}
inline void PaiGowPlayer::set_is_banker(bool value) {
  
  is_banker_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowPlayer.is_banker)
}

// uint32 status = 4;
inline void PaiGowPlayer::clear_status() {
  status_ = 0u;
}
inline ::google::protobuf::uint32 PaiGowPlayer::status() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowPlayer.status)
  return status_;
}
inline void PaiGowPlayer::set_status(::google::protobuf::uint32 value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowPlayer.status)
}

// repeated uint32 chips = 5;
inline int PaiGowPlayer::chips_size() const {
  return chips_.size();
}
inline void PaiGowPlayer::clear_chips() {
  chips_.Clear();
}
inline ::google::protobuf::uint32 PaiGowPlayer::chips(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowPlayer.chips)
  return chips_.Get(index);
}
inline void PaiGowPlayer::set_chips(int index, ::google::protobuf::uint32 value) {
  chips_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowPlayer.chips)
}
inline void PaiGowPlayer::add_chips(::google::protobuf::uint32 value) {
  chips_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.PaiGowPlayer.chips)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
PaiGowPlayer::chips() const {
  // @@protoc_insertion_point(field_list:proto3_proto.PaiGowPlayer.chips)
  return chips_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
PaiGowPlayer::mutable_chips() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.PaiGowPlayer.chips)
  return &chips_;
}

// int32 score = 6;
inline void PaiGowPlayer::clear_score() {
  score_ = 0;
}
inline ::google::protobuf::int32 PaiGowPlayer::score() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowPlayer.score)
  return score_;
}
inline void PaiGowPlayer::set_score(::google::protobuf::int32 value) {
  
  score_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowPlayer.score)
}

// -------------------------------------------------------------------

// PaiGowResult

// uint32 seat_id = 1;
inline void PaiGowResult::clear_seat_id() {
  seat_id_ = 0u;
}
inline ::google::protobuf::uint32 PaiGowResult::seat_id() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowResult.seat_id)
  return seat_id_;
}
inline void PaiGowResult::set_seat_id(::google::protobuf::uint32 value) {
  
  seat_id_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowResult.seat_id)
}

// int32 result = 2;
inline void PaiGowResult::clear_result() {
  result_ = 0;
}
inline ::google::protobuf::int32 PaiGowResult::result() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowResult.result)
  return result_;
}
inline void PaiGowResult::set_result(::google::protobuf::int32 value) {
  
  result_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowResult.result)
}

// repeated uint32 hand_cards = 3;
inline int PaiGowResult::hand_cards_size() const {
  return hand_cards_.size();
}
inline void PaiGowResult::clear_hand_cards() {
  hand_cards_.Clear();
}
inline ::google::protobuf::uint32 PaiGowResult::hand_cards(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowResult.hand_cards)
  return hand_cards_.Get(index);
}
inline void PaiGowResult::set_hand_cards(int index, ::google::protobuf::uint32 value) {
  hand_cards_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowResult.hand_cards)
}
inline void PaiGowResult::add_hand_cards(::google::protobuf::uint32 value) {
  hand_cards_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.PaiGowResult.hand_cards)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
PaiGowResult::hand_cards() const {
  // @@protoc_insertion_point(field_list:proto3_proto.PaiGowResult.hand_cards)
  return hand_cards_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
PaiGowResult::mutable_hand_cards() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.PaiGowResult.hand_cards)
  return &hand_cards_;
}

// -------------------------------------------------------------------

// PaiGowSnapshot

// uint32 state = 1;
inline void PaiGowSnapshot::clear_state() {
  state_ = 0u;
}
inline ::google::protobuf::uint32 PaiGowSnapshot::state() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowSnapshot.state)
  return state_;
}
inline void PaiGowSnapshot::set_state(::google::protobuf::uint32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowSnapshot.state)
}

// int64 room_owner = 2;
inline void PaiGowSnapshot::clear_room_owner() {
  room_owner_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 PaiGowSnapshot::room_owner() const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowSnapshot.room_owner)
  return room_owner_;
}
inline void PaiGowSnapshot::set_room_owner(::google::protobuf::int64 value) {
  
  room_owner_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowSnapshot.room_owner)
}

// repeated uint32 public_cards = 3;
inline int PaiGowSnapshot::public_cards_size() const {
  return public_cards_.size();
}
inline void PaiGowSnapshot::clear_public_cards() {
  public_cards_.Clear();
}
inline ::google::protobuf::uint32 PaiGowSnapshot::public_cards(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowSnapshot.public_cards)
  return public_cards_.Get(index);
}
inline void PaiGowSnapshot::set_public_cards(int index, ::google::protobuf::uint32 value) {
  public_cards_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.PaiGowSnapshot.public_cards)
}
inline void PaiGowSnapshot::add_public_cards(::google::protobuf::uint32 value) {
  public_cards_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.PaiGowSnapshot.public_cards)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
PaiGowSnapshot::public_cards() const {
  // @@protoc_insertion_point(field_list:proto3_proto.PaiGowSnapshot.public_cards)
  return public_cards_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
PaiGowSnapshot::mutable_public_cards() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.PaiGowSnapshot.public_cards)
  return &public_cards_;
}

// repeated .proto3_proto.PaiGowPlayer players = 4;
inline int PaiGowSnapshot::players_size() const {
  return players_.size();
}
inline void PaiGowSnapshot::clear_players() {
  players_.Clear();
}
inline const ::proto3_proto::PaiGowPlayer& PaiGowSnapshot::players(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowSnapshot.players)
  return players_.Get(index);
}
inline ::proto3_proto::PaiGowPlayer* PaiGowSnapshot::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:proto3_proto.PaiGowSnapshot.players)
  return players_.Mutable(index);
}
inline ::proto3_proto::PaiGowPlayer* PaiGowSnapshot::add_players() {
  // @@protoc_insertion_point(field_add:proto3_proto.PaiGowSnapshot.players)
  return players_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowPlayer >*
PaiGowSnapshot::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.PaiGowSnapshot.players)
  return &players_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowPlayer >&
PaiGowSnapshot::players() const {
  // @@protoc_insertion_point(field_list:proto3_proto.PaiGowSnapshot.players)
  return players_;
}

// repeated .proto3_proto.PaiGowResult results = 5;
inline int PaiGowSnapshot::results_size() const {
  return results_.size();
}
inline void PaiGowSnapshot::clear_results() {
  results_.Clear();
}
inline const ::proto3_proto::PaiGowResult& PaiGowSnapshot::results(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.PaiGowSnapshot.results)
  return results_.Get(index);
}
inline ::proto3_proto::PaiGowResult* PaiGowSnapshot::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:proto3_proto.PaiGowSnapshot.results)
  return results_.Mutable(index);
}
inline ::proto3_proto::PaiGowResult* PaiGowSnapshot::add_results() {
  // @@protoc_insertion_point(field_add:proto3_proto.PaiGowSnapshot.results)
  return results_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult >*
PaiGowSnapshot::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.PaiGowSnapshot.results)
  return &results_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult >&
PaiGowSnapshot::results() const {
  // @@protoc_insertion_point(field_list:proto3_proto.PaiGowSnapshot.results)
  return results_;
}

// -------------------------------------------------------------------

// S2C_PG_AddPlayer

// .proto3_proto.PaiGowPlayer player = 1;
inline bool S2C_PG_AddPlayer::has_player() const {
  return this != internal_default_instance() && player_ != NULL;
}
inline void S2C_PG_AddPlayer::clear_player() {
  if (GetArenaNoVirtual() == NULL && player_ != NULL) delete player_;
  player_ = NULL;
}
inline const ::proto3_proto::PaiGowPlayer& S2C_PG_AddPlayer::player() const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_AddPlayer.player)
  return player_ != NULL ? *player_
                         : *::proto3_proto::PaiGowPlayer::internal_default_instance();
}
inline ::proto3_proto::PaiGowPlayer* S2C_PG_AddPlayer::mutable_player() {
  
  if (player_ == NULL) {
    player_ = new ::proto3_proto::PaiGowPlayer;
  }
  // @@protoc_insertion_point(field_mutable:proto3_proto.S2C_PG_AddPlayer.player)
  return player_;
}
inline ::proto3_proto::PaiGowPlayer* S2C_PG_AddPlayer::release_player() {
  // @@protoc_insertion_point(field_release:proto3_proto.S2C_PG_AddPlayer.player)
  
  ::proto3_proto::PaiGowPlayer* temp = player_;
  player_ = NULL;
  return temp;
}
inline void S2C_PG_AddPlayer::set_allocated_player(::proto3_proto::PaiGowPlayer* player) {
  delete player_;
  player_ = player;
  if (player) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:proto3_proto.S2C_PG_AddPlayer.player)
}

// -------------------------------------------------------------------

// C2S_PG_StartGame

// -------------------------------------------------------------------

// S2C_PG_StartGame

// bool is_grab = 1;
inline void S2C_PG_StartGame::clear_is_grab() {
  is_grab_ = false;
}
inline bool S2C_PG_StartGame::is_grab() const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_StartGame.is_grab)
  return is_grab_;
}
inline void S2C_PG_StartGame::set_is_grab(bool value) {
  
  is_grab_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.S2C_PG_StartGame.is_grab)
}

// -------------------------------------------------------------------

// C2S_PG_GrabBanker

// bool is_grab = 1;
inline void C2S_PG_GrabBanker::clear_is_grab() {
  is_grab_ = false;
}
inline bool C2S_PG_GrabBanker::is_grab() const {
  // @@protoc_insertion_point(field_get:proto3_proto.C2S_PG_GrabBanker.is_grab)
  return is_grab_;
}
inline void C2S_PG_GrabBanker::set_is_grab(bool value) {
  
  is_grab_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.C2S_PG_GrabBanker.is_grab)
}

// -------------------------------------------------------------------

// S2C_PG_GrabBanker

// bool is_grab = 1;
inline void S2C_PG_GrabBanker::clear_is_grab() {
  is_grab_ = false;
}
inline bool S2C_PG_GrabBanker::is_grab() const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_GrabBanker.is_grab)
  return is_grab_;
}
inline void S2C_PG_GrabBanker::set_is_grab(bool value) {
  
  is_grab_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.S2C_PG_GrabBanker.is_grab)
}

// -------------------------------------------------------------------

// C2S_PG_Bet

// repeated uint32 chips = 1;
inline int C2S_PG_Bet::chips_size() const {
  return chips_.size();
}
inline void C2S_PG_Bet::clear_chips() {
  chips_.Clear();
}
inline ::google::protobuf::uint32 C2S_PG_Bet::chips(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.C2S_PG_Bet.chips)
  return chips_.Get(index);
}
inline void C2S_PG_Bet::set_chips(int index, ::google::protobuf::uint32 value) {
  chips_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.C2S_PG_Bet.chips)
}
inline void C2S_PG_Bet::add_chips(::google::protobuf::uint32 value) {
  chips_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.C2S_PG_Bet.chips)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
C2S_PG_Bet::chips() const {
  // @@protoc_insertion_point(field_list:proto3_proto.C2S_PG_Bet.chips)
  return chips_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
C2S_PG_Bet::mutable_chips() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.C2S_PG_Bet.chips)
  return &chips_;
}

// -------------------------------------------------------------------

// S2C_PG_Bet

// int64 user_id = 1;
inline void S2C_PG_Bet::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 S2C_PG_Bet::user_id() const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_Bet.user_id)
  return user_id_;
}
inline void S2C_PG_Bet::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.S2C_PG_Bet.user_id)
}

// repeated uint32 chips = 2;
inline int S2C_PG_Bet::chips_size() const {
  return chips_.size();
}
inline void S2C_PG_Bet::clear_chips() {
  chips_.Clear();
}
inline ::google::protobuf::uint32 S2C_PG_Bet::chips(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_Bet.chips)
  return chips_.Get(index);
}
inline void S2C_PG_Bet::set_chips(int index, ::google::protobuf::uint32 value) {
  chips_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.S2C_PG_Bet.chips)
}
inline void S2C_PG_Bet::add_chips(::google::protobuf::uint32 value) {
  chips_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.S2C_PG_Bet.chips)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
S2C_PG_Bet::chips() const {
  // @@protoc_insertion_point(field_list:proto3_proto.S2C_PG_Bet.chips)
  return chips_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
S2C_PG_Bet::mutable_chips() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.S2C_PG_Bet.chips)
  return &chips_;
}

// -------------------------------------------------------------------

// S2C_PG_Deal

// repeated uint32 my_card = 1;
inline int S2C_PG_Deal::my_card_size() const {
  return my_card_.size();
}
inline void S2C_PG_Deal::clear_my_card() {
  my_card_.Clear();
}
inline ::google::protobuf::uint32 S2C_PG_Deal::my_card(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_Deal.my_card)
  return my_card_.Get(index);
}
inline void S2C_PG_Deal::set_my_card(int index, ::google::protobuf::uint32 value) {
  my_card_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.S2C_PG_Deal.my_card)
}
inline void S2C_PG_Deal::add_my_card(::google::protobuf::uint32 value) {
  my_card_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.S2C_PG_Deal.my_card)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
S2C_PG_Deal::my_card() const {
  // @@protoc_insertion_point(field_list:proto3_proto.S2C_PG_Deal.my_card)
  return my_card_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
S2C_PG_Deal::mutable_my_card() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.S2C_PG_Deal.my_card)
  return &my_card_;
}

// -------------------------------------------------------------------

// C2S_PG_Collocation

// repeated uint32 first = 1;
inline int C2S_PG_Collocation::first_size() const {
  return first_.size();
}
inline void C2S_PG_Collocation::clear_first() {
  first_.Clear();
}
inline ::google::protobuf::uint32 C2S_PG_Collocation::first(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.C2S_PG_Collocation.first)
  return first_.Get(index);
}
inline void C2S_PG_Collocation::set_first(int index, ::google::protobuf::uint32 value) {
  first_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.C2S_PG_Collocation.first)
}
inline void C2S_PG_Collocation::add_first(::google::protobuf::uint32 value) {
  first_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.C2S_PG_Collocation.first)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
C2S_PG_Collocation::first() const {
  // @@protoc_insertion_point(field_list:proto3_proto.C2S_PG_Collocation.first)
  return first_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
C2S_PG_Collocation::mutable_first() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.C2S_PG_Collocation.first)
  return &first_;
}

// repeated uint32 end = 2;
inline int C2S_PG_Collocation::end_size() const {
  return end_.size();
}
inline void C2S_PG_Collocation::clear_end() {
  end_.Clear();
}
inline ::google::protobuf::uint32 C2S_PG_Collocation::end(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.C2S_PG_Collocation.end)
  return end_.Get(index);
}
inline void C2S_PG_Collocation::set_end(int index, ::google::protobuf::uint32 value) {
  end_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.C2S_PG_Collocation.end)
}
inline void C2S_PG_Collocation::add_end(::google::protobuf::uint32 value) {
  end_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.C2S_PG_Collocation.end)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
C2S_PG_Collocation::end() const {
  // @@protoc_insertion_point(field_list:proto3_proto.C2S_PG_Collocation.end)
  return end_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
C2S_PG_Collocation::mutable_end() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.C2S_PG_Collocation.end)
  return &end_;
}

// -------------------------------------------------------------------

// S2C_PG_Collocation

// uint32 seat_id = 1;
inline void S2C_PG_Collocation::clear_seat_id() {
  seat_id_ = 0u;
}
inline ::google::protobuf::uint32 S2C_PG_Collocation::seat_id() const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_Collocation.seat_id)
  return seat_id_;
}
inline void S2C_PG_Collocation::set_seat_id(::google::protobuf::uint32 value) {
  
  seat_id_ = value;
  // @@protoc_insertion_point(field_set:proto3_proto.S2C_PG_Collocation.seat_id)
}

// repeated uint32 cards = 2;
inline int S2C_PG_Collocation::cards_size() const {
  return cards_.size();
}
inline void S2C_PG_Collocation::clear_cards() {
  cards_.Clear();
}
inline ::google::protobuf::uint32 S2C_PG_Collocation::cards(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_Collocation.cards)
  return cards_.Get(index);
}
inline void S2C_PG_Collocation::set_cards(int index, ::google::protobuf::uint32 value) {
  cards_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.S2C_PG_Collocation.cards)
}
inline void S2C_PG_Collocation::add_cards(::google::protobuf::uint32 value) {
  cards_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.S2C_PG_Collocation.cards)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
S2C_PG_Collocation::cards() const {
  // @@protoc_insertion_point(field_list:proto3_proto.S2C_PG_Collocation.cards)
  return cards_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
S2C_PG_Collocation::mutable_cards() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.S2C_PG_Collocation.cards)
  return &cards_;
}

// -------------------------------------------------------------------

// S2C_PG_Result

// repeated .proto3_proto.PaiGowResult scores = 1;
inline int S2C_PG_Result::scores_size() const {
  return scores_.size();
}
inline void S2C_PG_Result::clear_scores() {
  scores_.Clear();
}
inline const ::proto3_proto::PaiGowResult& S2C_PG_Result::scores(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_Result.scores)
  return scores_.Get(index);
}
inline ::proto3_proto::PaiGowResult* S2C_PG_Result::mutable_scores(int index) {
  // @@protoc_insertion_point(field_mutable:proto3_proto.S2C_PG_Result.scores)
  return scores_.Mutable(index);
}
inline ::proto3_proto::PaiGowResult* S2C_PG_Result::add_scores() {
  // @@protoc_insertion_point(field_add:proto3_proto.S2C_PG_Result.scores)
  return scores_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult >*
S2C_PG_Result::mutable_scores() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.S2C_PG_Result.scores)
  return &scores_;
}
inline const ::google::protobuf::RepeatedPtrField< ::proto3_proto::PaiGowResult >&
S2C_PG_Result::scores() const {
  // @@protoc_insertion_point(field_list:proto3_proto.S2C_PG_Result.scores)
  return scores_;
}

// repeated uint32 public_cards = 2;
inline int S2C_PG_Result::public_cards_size() const {
  return public_cards_.size();
}
inline void S2C_PG_Result::clear_public_cards() {
  public_cards_.Clear();
}
inline ::google::protobuf::uint32 S2C_PG_Result::public_cards(int index) const {
  // @@protoc_insertion_point(field_get:proto3_proto.S2C_PG_Result.public_cards)
  return public_cards_.Get(index);
}
inline void S2C_PG_Result::set_public_cards(int index, ::google::protobuf::uint32 value) {
  public_cards_.Set(index, value);
  // @@protoc_insertion_point(field_set:proto3_proto.S2C_PG_Result.public_cards)
}
inline void S2C_PG_Result::add_public_cards(::google::protobuf::uint32 value) {
  public_cards_.Add(value);
  // @@protoc_insertion_point(field_add:proto3_proto.S2C_PG_Result.public_cards)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
S2C_PG_Result::public_cards() const {
  // @@protoc_insertion_point(field_list:proto3_proto.S2C_PG_Result.public_cards)
  return public_cards_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
S2C_PG_Result::mutable_public_cards() {
  // @@protoc_insertion_point(field_mutable_list:proto3_proto.S2C_PG_Result.public_cards)
  return &public_cards_;
}

// -------------------------------------------------------------------

// C2S_PG_Sure

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto3_proto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_paigow_2eproto__INCLUDED
